# Read the Docs configuration file.
# Doc: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

mkdocs:
  configuration: docsmk/mkdocs.yml

build:
  tools:
    python: 3  # Last stable CPython version

python:
  install:
  - requirements: docsmk/requirements.txt
